spring.application.name=my-pocket-movie-api

spring.datasource.url=jdbc:mysql://localhost:3306/mypocket?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=13243546
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

springdoc.swagger-ui.path=/swagger-ui.html

# TMDB API Key
tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.api.access-token=4f5b5d2e5a6e93c0045482be1aa6e6a8